export const MAX_OFFSET_YEAR = 5000;
export const MIN_OFFSET_YEAR = 0;
export const NUMBERS_OF_MONTHS = 12;

// DRAG WITH SCROLLBAR ITEM
export const DISTANCE_SCROLLBAR_BOUNCE = 32;
export const DISTANCE_TO_CHECK_BOUNCE_OF_SCROLLBAR = 4
